export default {
    "sexual_activity": [
        { "id": "1", "title": "unprotected_sex", "emoji": "🤰🏻" },
        { "id": "2", "title": "protected_sex", "emoji": "🙆🏻‍♀️" },
        { "id": "3", "title": "masturbation", "emoji": "💦" },
        { "id": "4", "title": "kissing", "emoji": "😚" }
    ],
    "symptoms_activity": [
        { "id": "5", "title": "bloating", "emoji": "🤢" },
        { "id": "6", "title": "cramps", "emoji": "😖" },
        { "id": "7", "title": "gas", "emoji": "💨" },
        { "id": "8", "title": "headaches", "emoji": "🤕" },
        { "id": "9", "title": "spotting_bleeding", "emoji": "🩸" },
        { "id": "10", "title": "acne", "emoji": "🌋" },
        { "id": "11", "title": "anxiety", "emoji": "😰" },
        { "id": "13", "title": "breast_sensitivity", "emoji": "🌸" },
        { "id": "14", "title": "breast_tenderness", "emoji": "❤️" },
        { "id": "15", "title": "chills", "emoji": "❄️" },
        { "id": "16", "title": "confusion", "emoji": "😕" },
        { "id": "17", "title": "constipation", "emoji": "💩" },
        { "id": "18", "title": "cravings", "emoji": "🍰" },
        { "id": "19", "title": "diarrhea", "emoji": "🤒" },
        { "id": "20", "title": "dyspepsia", "emoji": "🥴" },
        { "id": "21", "title": "flow", "emoji": "🌊" },
        { "id": "22", "title": "fever", "emoji": "🌡️" },
        { "id": "23", "title": "hot_flashes", "emoji": "🔥" },
        { "id": "24", "title": "hunger", "emoji": "🍽️" },
        { "id": "25", "title": "insomnia", "emoji": "😴" },
        { "id": "26", "title": "irritability", "emoji": "😒" },
        { "id": "27", "title": "itchiness", "emoji": "" },
        { "id": "28", "title": "migraines", "emoji": "🤯" },
        { "id": "29", "title": "moodiness", "emoji": "😠" },
        { "id": "30", "title": "muscle_pain", "emoji": "💪" },
        { "id": "31", "title": "pms", "emoji": "🤬" },
        { "id": "33", "title": "rashes", "emoji": "👪" },
        { "id": "34", "title": "stress", "emoji": "😓" },
        { "id": "35", "title": "tension", "emoji": "😡" },
        { "id": "36", "title": "unable_to_concentrate", "emoji": "🤔" },
        { "id": "37", "title": "weight_gain", "emoji": "⚖️" }
    ],
    "moods": [
        { "id": "38", "title": "happy", "emoji": "😊" },
        { "id": "39", "title": "sad", "emoji": "😢" },
        { "id": "40", "title": "angry", "emoji": "😡" },
        { "id": "41", "title": "surprised", "emoji": "😲" },
        { "id": "42", "title": "excited", "emoji": "😃" },
        { "id": "43", "title": "laughing", "emoji": "😂" },
        { "id": "44", "title": "embarrassed", "emoji": "😳" },
        { "id": "45", "title": "confused", "emoji": "😕" },
        { "id": "46", "title": "in_love", "emoji": "😍" },
        { "id": "47", "title": "tired_sleepy", "emoji": "😴" }
    ],
    "contraception": [
        { "id": "48", "title": "birth_control_pills", "emoji": "💊" },
        { "id": "49", "title": "contraceptive_patch", "emoji": "🩹" },
        { "id": "50", "title": "female_condom", "emoji": "☂️" },
        { "id": "51", "title": "contraceptive_ring", "emoji": "⭕" },
        { "id": "52", "title": "injection", "emoji": "💉" },
        { "id": "53", "title": "implant", "emoji": "👩‍⚕️" }
    ]
}
