export default {
    "Sexual Activity": [
        { id: "1", title: "UnprotectedSex", emoji: '🤰🏻' },
        { id: "2", title: "ProtectedSex", emoji: '🙆🏻‍♀️' },
        { id: "3", title: "Masturbation", emoji: '💦' },
        { id: "4", title: "Kissing", emoji: '😚' }
    ],
    "Symptoms Activity": [
        { id: "5", title: "Bloating", emoji: '🤢' },
        { id: "6", title: "Cramps", emoji: '😖' },
        { id: "7", title: "Gas", emoji: '💨' },
        { id: "8", title: "Headaches", emoji: '🤕' },
        { id: "9", title: "Spotting/Bleeding", emoji: '🩸' },
        { id: "10", title: "Acne", emoji: '🌋' },
        { id: "11", title: "Anxiety", emoji: '😰' },
        { id: "13", title: "Breast sensitivity", emoji: '🌸' },
        { id: "14", title: "Breast tenderness", emoji: '❤️' },
        { id: "15", title: "Chills", emoji: '❄️' },
        { id: "16", title: "Confusion", emoji: '😕' },
        { id: "17", title: "Constipation", emoji: '💩' },
        { id: "18", title: "Cravings", emoji: '🍰' },
        { id: "19", title: "Diarrhea", emoji: '🤒' },
        { id: "20", title: "Dyspepsia", emoji: '🥴' },
        { id: "21", title: "Flow", emoji: '🌊' },
        { id: "22", title: "Fever", emoji: '🌡️' },
        { id: "23", title: "Hot flashes", emoji: '🔥' },
        { id: "24", title: "Hunger", emoji: '🍽️' },
        { id: "25", title: "Insomnia", emoji: '😴' },
        { id: "26", title: "Irritability", emoji: '😒' },
        { id: "27", title: "Itchiness", emoji: '' },
        { id: "28", title: "Migraines", emoji: '🤯' },
        { id: "29", title: "Moodiness", emoji: '😠' },
        { id: "30", title: "Muscle pain", emoji: '💪' },
        { id: "31", title: "PMS", emoji: '🤬' },
        { id: "33", title: "Rashes", emoji: '👪' },
        { id: "34", title: "Stress", emoji: '😓' },
        { id: "35", title: "Tension", emoji: '😡' },
        { id: "36", title: "Unable to concentrate", emoji: '🤔' },
        { id: "37", title: "Weight gain", emoji: '⚖️' }
    ],
    "Moods": [
        { id: "38", title: "Happy", emoji: '😊' },
        { id: "39", title: "Sad", emoji: '😢' },
        { id: "40", title: "Angry", emoji: '😡' },
        { id: "41", title: "Surprised", emoji: '😲' },
        { id: "42", title: "Excited", emoji: '😃' },
        { id: "43", title: "Laughing", emoji: '😂' },
        { id: "44", title: "Embarrassed", emoji: '😳' },
        { id: "45", title: "Confused", emoji: '😕' },
        { id: "46", title: "In Love", emoji: '😍' },
        { id: "47", title: "Tired/Sleepy", emoji: '😴' }
    ],
    "Contraception": [
        { id: "48", title: "Birth Control Pills", emoji: '💊' },
        { id: "49", title: "Contraceptive Patch", emoji: "🩹" },
        { id: "50", title: "Female Condom", emoji: '☂️' },
        { id: "51", title: "Contraceptive Ring", emoji: '⭕' },
        { id: "52", title: "Injection", emoji: '💉' },
        { id: "53", title: "Implant", emoji: '👩‍⚕️' },
    ]
}
